### ISSUE TITLE
How to query data

### ISSUE THREAD

**Issue by luizkowalski** [stripe/mosql#84]
I have an app using mongo (mongoid), and now, I want to send some collections to postgres, and query this data on this app.
The documentation is not clear about how I can do that or if I'm able to do this.
Is this possible?

**Comment by loganfuller** [comment]
Querying the data would be the same as querying any SQL database and doesn't need the MoSQL daemon. I recommend PGAdmin as a GUI, otherwise you can just use the psql command line tool.

**Comment by luizkowalski** [comment]
No, I mean, I want to send all writes to mongodb and some reads to pgsql
I think this is not a mosql problem
