### ISSUE TITLE
Unable to resolve dependencies using gem install

### ISSUE THREAD

**Issue by benjaminaschultz** [stripe/mosql#91]
When I try to install [the mosql gem](https://rubygems.org/gems/mosql) I get the following error

```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: mosql requires bson (~> 1.10); bson_ext requires bson (~> 1.12.1)
```
 There is also a problem with the `mongo` requirement which requires `bson (~>3.0)`

Instead requiring `bson_ext (~> 1.10)` and `mongo (~>1.10.0)` ought to fix the issue.  I was able to get it up and running by installing
```
mongo 1.10.0
bson 1.10.2
bson_ext 1.10.0
```
and building the gem. Don't know if this is cause by ancient repos or what, but figured I'd let some know :)

**Comment by nelhage** [comment]
I just pushed a 0.4.3 – does that resolve your issue? Our dependencies in the gem are unfortunately sloppy at present :(

**Comment by benjaminaschultz** [comment]
Yep! That works for me now.
